apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  # Ambassador config module: https://www.getambassador.io/docs/edge-stack/latest/topics/running/ambassador/#the-module-resource
  config:
    # Envoy Lua docs: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter
    lua_scripts: |
      function envoy_on_response(handle)
        -- handle:body():setBytes("<html><b>Override!</b></html>")
        local responseBody = handle:body()

        local headers, body = handle:httpCall(
          "cluster_bff_mock_ambassador",
          {
            [":method"] = "GET",
            [":path"] = "/bff",
            [":authority"] = "bff-mock",
            ["x-error-code"] = "TEST"
          }, "", 5000)

        handle:logInfo(#body)

        handle:headers():add("lua-filter", body:getBytes(0, 15))
        handle:headers():add("lua-filter-x", responseBody:getBytes(0, 15))

        responseBody:setBytes(body)
      end
