apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  # Ambassador config module: https://www.getambassador.io/docs/edge-stack/latest/topics/running/ambassador/#the-module-resource
  config:
    # Envoy Lua docs: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter
    lua_scripts: |
      function envoy_on_request(request_handle)
        request_handle:respond(
          { [":status"] = "301",
            ["Location"] = "https://www.baidu.com" },
          "<html><body>Redirecting</body></html>"
        )
      end
      function envoy_on_response(response_handle)
        response_handle:headers():add("Lua-Scripts-Enabled", "Processed")
      end
