---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: bff-mock
  namespace: ambassador
spec:
  prefix: /bff-mock/
  service: bff-mock
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: bff-mock-v2
  namespace: ambassador
spec:
  prefix: /bff-mock-v2/
  service: bff-mock:81
