---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: domain-service-mock
  namespace: ambassador
spec:
  prefix: /domain-service-mock/
  service: domain-service-mock
---
apiVersion: v1
kind: Service
metadata:
  name: domain-service-mock
  namespace: ambassador
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: domain-service-mock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-service-mock
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-service-mock
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: domain-service-mock
    spec:
      containers:
        - name: domain-service-mock
          image: docker.io/dizy/domain-service-mock:latest
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: domain-service-mock-volume
              mountPath: "/etc/mock"
              readOnly: true
      volumes:
        - name: domain-service-mock-volume
          configMap:
            name: domain-service-mock-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-service-mock-config
  namespace: ambassador
data:
  domain-service-mock.json: |
    {
      "port": 3000,
      "failureRate": 0.5,
      "averageResponseTime": 300,
      "responseTimeDeviation": 100
    }
