---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: filter-policy
  namespace: ambassador
spec:
  rules:
    - host: "*"
      path: "/quote/"
      filters:
        - name: auth-service-http
